name: Fellowship Project CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - dev
jobs:
  docker-build-push:
    runs-on: [hello]
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Docker Tag
        id: docker_tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            TAG="dev-${GITHUB_SHA::7}"
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAG="latest"
          else
            TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      
      - name: Build and Push Backend1
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend1:${{ steps.docker_tag.outputs.tag }} ./code/backend1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend1:${{ steps.docker_tag.outputs.tag }}
      
